workflows:
  Instagram-workflow:
    name: Instagram Pipiline
    scripts:
     -  name: CICD Started
        script: echo "Welcome to your CICD set up"
     - name: Build Instagram
       script: xcodebuild build -workspace "Instagram.xcworkspace" -scheme "Instagram" CODE_SIGN_IDENTITY=""CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
        email:
            recipients:
                - gu2003.mendonca48@gmail.com
