workflows:
  Instagram-workflow:
    name: Instagram Pipiline
    scripts:
     -  name: CICD Started
        script: echo "Welcome to your CICD set up"
    publishing:
        email:
            recipients:
                - gu2003.mendonca48@gmail.com
